### ISSUE TITLE
Not working with Gnome 3.38

### ISSUE THREAD

**Issue by Teddytrombone** [se1exin/unix-timestamp-clock#2]
I had to replace `x_fill` and `y_fill` with `x_expand` and `y_expand` on lines 16 and 17 in extension.js

**Comment by se1exin** [comment]
Thanks @Teddytrombone. Updated master and in review at https://extensions.gnome.org/review/20032. Will close when this issue when approved.

**Comment by se1exin** [comment]
https://extensions.gnome.org/review/20032 has been approved
